[package]
name = "merchant_inv_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
serde = { version = "1.0.217", features = ["derive"] }
ron = "0.8.1"
lazy_static = "1.5.0"
enum-derived = "0.8.2"

[build-dependencies]
ron = "0.8.1"
serde = { version = "1.0.217", features = ["derive"] }
